- name: "Include set_file_state tasks"
  when:
    - aspects_file_tasks_set_file_state_enabled
  include_tasks: set_file_state.yml
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "Include set_file_contents tasks"
  when:
    - aspects_file_tasks_set_file_contents_enabled
  include_tasks: set_file_contents.yml
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_contents"
    - "aspects_file_tasks_set_file_contents_upload"
    - "aspects_file_tasks_set_file_contents_template"
    - "aspects_file_tasks_set_file_contents_template_plain"
    - "aspects_file_tasks_set_file_contents_template_yaml"
    - "aspects_file_tasks_set_line_contents"


- name: "Include set_file_contents_cas tasks"
  when:
    - aspects_file_tasks_set_file_contents_cas_enabled
  include_tasks: set_file_contents_cas.yml
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_contents"
    - "aspects_file_tasks_set_file_contents_cas"
