- name: "set_file_state - Set general file or directory state."
  run_once: false
  when:
    - ( item.1.run_once is not defined or item.1.run_once == false )
    - item.1.enabled or item.1.enabled == "True"
    - (
      item.1.state == "file" or
      item.1.state == "directory" or
      item.1.state == "touch"
      )
  file:
    state: "{{ item.1.state }}"
    dest: "{{ item.1.dest }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dictsort }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "set_file_state - Run once - Set general file or directory state."
  run_once: true
  when:
    - item.1.run_once is defined and item.1.run_once == true
    - item.1.enabled or item.1.enabled == "True"
    - (
      item.1.state == "file" or
      item.1.state == "directory" or
      item.1.state == "touch"
      )
  file:
    state: "{{ item.1.state }}"
    dest: "{{ item.1.dest }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dictsort }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "set_file_state - Set general file or directory state."
  run_once: false
  when:
    - ( item.1.run_once is not defined or item.1.run_once == false )
    - item.1.enabled or item.1.enabled == "True"
    - (
      item.1.state == "link" or
      item.1.state == "hard"
      )
  file:
    state: "{{ item.1.state }}"
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dictsort }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "set_file_state - Run Once - Set general file or directory state."
  run_once: true
  when:
    - item.1.run_once is defined and item.1.run_once == true
    - item.1.enabled or item.1.enabled == "True"
    - (
      item.1.state == "link" or
      item.1.state == "hard"
      )
  file:
    state: "{{ item.1.state }}"
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dictsort }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "set_file_state - Delete general file or directory."
  run_once: false
  when:
    - ( item.1.run_once is not defined or item.1.run_once == false )
    - item.1.enabled or item.1.enabled == "True"
    - item.1.state == "absent"
  file:
    state: "{{ item.1.state }}"
    dest: "{{ item.1.dest }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dictsort }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "set_file_state - Run Once - Delete general file or directory."
  run_once: true
  when:
    - item.1.run_once is defined and item.1.run_once == true
    - item.1.enabled or item.1.enabled == "True"
    - item.1.state == "absent"
  file:
    state: "{{ item.1.state }}"
    dest: "{{ item.1.dest }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dictsort }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"