- name: "Set general file or directory state."
  when:
    - item.1.enabled or item.1.enabled == "True"
    - (
        item.1.state == "file" or
        item.1.state == "directory" or
        item.1.state == "touch"
      )
  file:
    state: "{{ item.1.state }}"
    dest: "{{ item.1.dest }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dict2items }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "Set general file or directory state."
  when:
    - item.1.enabled or item.1.enabled == "True"
    - (
      item.1.state == "link" or
      item.1.state == "hard"
      )
  file:
    state: "{{ item.1.state }}"
    src: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    owner: "{{ item.1.owner }}"
    group: "{{ item.1.group }}"
    mode: "{{ item.1.mode }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dict2items }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"

- name: "Delete general file or directory."
  when:
    - item.1.enabled or item.1.enabled == "True"
    - item.1.state == "absent"
  file:
    state: "{{ item.1.state }}"
    dest: "{{ item.1.dest }}"
  loop: "{{ aspects_file_tasks_set_file_state_items | default({}) | dict2items }}"
  tags:
    - "aspects_file_tasks"
    - "aspects_file_tasks_set_file_state"